// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsOVa7j-m9GQdWDdih77x8VfFXKxCP1JM',
    appId: '1:1038077548119:web:0455dd6e560e4b9fcd3512',
    messagingSenderId: '1038077548119',
    projectId: 'weather-app-1c4fa',
    authDomain: 'weather-app-1c4fa.firebaseapp.com',
    databaseURL: 'https://weather-app-1c4fa-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-1c4fa.firebasestorage.app',
    measurementId: 'G-M3WD90PH38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsg5tPtyEVMLrnty3HNbeagTpklU0Zp9M',
    appId: '1:1038077548119:android:6d55241c932342decd3512',
    messagingSenderId: '1038077548119',
    projectId: 'weather-app-1c4fa',
    databaseURL: 'https://weather-app-1c4fa-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-1c4fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4m1QIN83pXtdMDmLVjz_36VH7GNemyuU',
    appId: '1:1038077548119:ios:f6c7e61b8e5768b5cd3512',
    messagingSenderId: '1038077548119',
    projectId: 'weather-app-1c4fa',
    databaseURL: 'https://weather-app-1c4fa-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-1c4fa.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4m1QIN83pXtdMDmLVjz_36VH7GNemyuU',
    appId: '1:1038077548119:ios:f6c7e61b8e5768b5cd3512',
    messagingSenderId: '1038077548119',
    projectId: 'weather-app-1c4fa',
    databaseURL: 'https://weather-app-1c4fa-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-1c4fa.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsOVa7j-m9GQdWDdih77x8VfFXKxCP1JM',
    appId: '1:1038077548119:web:2b242857e46bdc47cd3512',
    messagingSenderId: '1038077548119',
    projectId: 'weather-app-1c4fa',
    authDomain: 'weather-app-1c4fa.firebaseapp.com',
    databaseURL: 'https://weather-app-1c4fa-default-rtdb.firebaseio.com',
    storageBucket: 'weather-app-1c4fa.firebasestorage.app',
    measurementId: 'G-2J1YG80B1S',
  );

}